Language.delete_all
Language.create!([{language: "afrikaans", language_code: "af"}])
Language.create!([{language: "latin", language_code: "bs-Latn"}])
Language.create!([{language: "catalan", language_code: "ca"}])
Language.create!([{language: "bulgarian", language_code: "bg"}])
Language.create!([{language: "czech", language_code: "cs"}])
Language.create!([{language: "danish", language_code: "da"}])
Language.create!([{language: "dutch", language_code: "nl"}])
Language.create!([{language: "estonian", language_code: "et"}])
Language.create!([{language: "finnish", language_code: "fi"}])
Language.create!([{language: "french", language_code: "fr"}])
Language.create!([{language: "german", language_code: "de"}])
Language.create!([{language: "italian", language_code: "it"}])
Language.create!([{language: "portuguese", language_code: "pt"}])
Language.create!([{language: "spanish", language_code: "es"}])
Language.create!([{language: "welsch", language_code: "cy"}])
